version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: intervyo-local-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_storage:/data/db
    restart: unless-stopped

volumes:
  mongo_storage:
 